# Project
group = dev.tophatcat.sprucewillisthexmastree
mod_name = Spruce Willis the Xmas Tree
mod_id = sprucewillisthexmastree
author = KiriCattus
credits = KiriCattus
license = MIT
license_description = A Minecraft mod made for WinterJam 2019, contains an Xmas tree named Spruce Willis.
description=A Minecraft mod made for WinterJam 2019. Bruce has evolved into Spruce Willis the Christmas Tree!

# Links
display_url = https://tophatcat.dev
discord = https://discord.tophatcat.dev
mod_source = https://github.com/kiris-mods/spruce-willis-the-xmas-tree
license_url = https://github.com/kiris-mods/spruce-willis-the-xmas-tree/blob/dev/LICENSE.md
modrinth_url=https://modrinth.com/mod/spruce-willis-the-xmas-tree
curseforge_url=https://curseforge.com/minecraft/mc-mods/spruce-willis-the-xmas-tree

# Common
java_version = 21
minecraft_version = 1.21.1
minecraft_version_range = [1.21,)
parchment_minecraft = 1.21.1
parchment_version = 2024.11.17
modrinth_id = E4DbrlAA
curseforge_id = 354046

# NeoForge
# See https://projects.neoforged.net/neoforged/moddevgradle for new versions
# See https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
mod_dev_version = 2.0.66-beta
neoforge_version = 21.1.92
neoforge_version_range = [21.1,)
fancy_mod_loader_version = 4.0.34
fancy_mod_loader_version_range = [4,)
neo_form_version = 1.21.1-20240808.144430

# Fabric
# See https://fabricmc.net/develop/ for new versions
fabric_loom = 1.9-SNAPSHOT
fabric_version = 0.114.0
fabric_version_range = >=0.114.0
fabric_loader_version = 0.16.9
fabric_loader_version_range = >=0.16

# Dependency versions
jade_neoforge_version = 15.9.2+neoforge

jade_fabric_version = 15.9.2+fabric
modmenu_version = 11.0.3

# Gradle
org.gradle.jvmargs = -Xmx3G
org.gradle.daemon = false
org.gradle.debug = false
